int _putchar(char);
int _isupper(int);
int _isdigit(int);
int mul(int a, int b);
void print_numbers(void);
void more_numbers(void);
void print_most_numbers(void);
void print_any_number(int);
void print_line(int n);
void print_diagonal(int n);
void print_square(int size);
void print_triangle(int size);
